name: branch-write
description: write contents on a certain branch
author: Yanqiao Chen

inputs:
  repo-token:
    description: "A token with the write access to the working repository"
    required: true
  branch:
    description: "A branch name you want to upload content"
    required: true
  path:
    description: "The destination path where you want to upload content"
    required: true
  source:
    description: "The source where you want to upload from:env, content or branch-and-path"
    required: true
  source-arg:
    description: "The argument associate with arg source. Could be env key, branch plus path or string content"
    required: true
  
runs:
  using: "composite"
  steps:
    - run: pip install --no-cache-dir --upgrade pip  && pip install --no-cache-dir requirements.txt
      shell: bash
    - run: python branchwrite.py ${{ inputs.branch }} ${{ inputs.path }} ${{ inputs.source }} ${{ inputs.source-arg }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        
branding:
  icon: git-branch
  color: blue
